package com.zubajie.entity;

import java.io.Serializable;

public class BorrowPicture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_picture.borrow_id
     *
     * @mbg.generated
     */
    private Integer borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_picture.photo_url
     *
     * @mbg.generated
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table borrow_picture
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_picture.borrow_id
     *
     * @return the value of borrow_picture.borrow_id
     *
     * @mbg.generated
     */
    public Integer getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_picture.borrow_id
     *
     * @param borrowId the value for borrow_picture.borrow_id
     *
     * @mbg.generated
     */
    public void setBorrowId(Integer borrowId) {
        this.borrowId = borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_picture.photo_url
     *
     * @return the value of borrow_picture.photo_url
     *
     * @mbg.generated
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_picture.photo_url
     *
     * @param photoUrl the value for borrow_picture.photo_url
     *
     * @mbg.generated
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_picture
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", borrowId=").append(borrowId);
        sb.append(", photoUrl=").append(photoUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}