package com.zubajie.entity;

import java.io.Serializable;
import java.util.Date;

public class ChatRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.user1_id
     *
     * @mbg.generated
     */
    private Integer user1Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.user2_id
     *
     * @mbg.generated
     */
    private Integer user2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_record.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.user1_id
     *
     * @return the value of chat_record.user1_id
     *
     * @mbg.generated
     */
    public Integer getUser1Id() {
        return user1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.user1_id
     *
     * @param user1Id the value for chat_record.user1_id
     *
     * @mbg.generated
     */
    public void setUser1Id(Integer user1Id) {
        this.user1Id = user1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.user2_id
     *
     * @return the value of chat_record.user2_id
     *
     * @mbg.generated
     */
    public Integer getUser2Id() {
        return user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.user2_id
     *
     * @param user2Id the value for chat_record.user2_id
     *
     * @mbg.generated
     */
    public void setUser2Id(Integer user2Id) {
        this.user2Id = user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.message
     *
     * @return the value of chat_record.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.message
     *
     * @param message the value for chat_record.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_record.time
     *
     * @return the value of chat_record.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_record.time
     *
     * @param time the value for chat_record.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", user1Id=").append(user1Id);
        sb.append(", user2Id=").append(user2Id);
        sb.append(", message=").append(message);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}