-- MySQL Script generated by MySQL Workbench
-- Mon Jul 15 15:49:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `nick_name` VARCHAR(45) NULL,
  `sex` TINYINT NOT NULL,
  `student_number` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `address` VARCHAR(150) NULL,
  `score` INT NOT NULL DEFAULT 100,
  `head_portrait` VARCHAR(150) NULL,
  `audit_picture` VARCHAR(150) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lend_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lend_goods` (
  `lend_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `create_time` DATE NOT NULL,
  `price` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `photo_number` INT NULL,
  `tag` VARCHAR(45) NULL,
  `title` VARCHAR(100) NULL,
  `period_of_validity` INT NULL,
  `state` TINYINT NULL,
  PRIMARY KEY (`lend_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`borrow_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`borrow_goods` (
  `borrow_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `create_time` DATE NULL,
  `price` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `photo_number` INT NULL,
  `tag` VARCHAR(45) NULL,
  `title` VARCHAR(100) NULL,
  `period_of_validity` INT NULL,
  `state` TINYINT NULL,
  PRIMARY KEY (`borrow_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`borrow_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`borrow_picture` (
  `borrow_id` INT NOT NULL,
  `photo_url` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`borrow_id`, `photo_url`),
  CONSTRAINT `borrow_id`
    FOREIGN KEY (`borrow_id`)
    REFERENCES `mydb`.`borrow_goods` (`borrow_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lend_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lend_picture` (
  `lend_id` INT NOT NULL,
  `photo_url` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`lend_id`, `photo_url`),
  CONSTRAINT `lend_id`
    FOREIGN KEY (`lend_id`)
    REFERENCES `mydb`.`lend_goods` (`lend_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_id` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `saler_id` INT NOT NULL,
  `time` DATE NOT NULL,
  `order_state` TINYINT NOT NULL,
  `goods_id` INT NOT NULL,
  `buyer_score` INT NULL,
  `saler_score` INT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `buyer_id_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `saler_id_idx` (`saler_id` ASC) VISIBLE,
  INDEX `goods_id_idx` (`goods_id` ASC) VISIBLE,
  CONSTRAINT `buyer_id`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `saler_id`
    FOREIGN KEY (`saler_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `goods_id`
    FOREIGN KEY (`goods_id`)
    REFERENCES `mydb`.`borrow_goods` (`borrow_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `goods_id`
    FOREIGN KEY (`goods_id`)
    REFERENCES `mydb`.`lend_goods` (`lend_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat_record` (
  `user1_id` INT NOT NULL,
  `user2_id` INT NOT NULL,
  `message` VARCHAR(200) NOT NULL,
  `time` DATE NOT NULL,
  PRIMARY KEY (`user1_id`, `user2_id`, `message`, `time`),
  INDEX `user2_id_idx` (`user2_id` ASC) VISIBLE,
  CONSTRAINT `user1_id`
    FOREIGN KEY (`user1_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user2_id`
    FOREIGN KEY (`user2_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`collect` (
  `user_id` INT NOT NULL,
  `goods_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `goods_id`),
  INDEX `goods_id_idx` (`goods_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `goods_id`
    FOREIGN KEY (`goods_id`)
    REFERENCES `mydb`.`borrow_goods` (`borrow_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `goods_id`
    FOREIGN KEY (`goods_id`)
    REFERENCES `mydb`.`lend_goods` (`lend_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
