package com.zubajie.dao;

import com.zubajie.entity.BorrowGoods;
import java.util.List;

public interface BorrowGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer borrowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_goods
     *
     * @mbg.generated
     */
    int insert(BorrowGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_goods
     *
     * @mbg.generated
     */
    BorrowGoods selectByPrimaryKey(Integer borrowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_goods
     *
     * @mbg.generated
     */
    List<BorrowGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BorrowGoods record);
}