package com.zubajie.dao;

import com.zubajie.entity.ChatRecord;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("user1Id") Integer user1Id, @Param("user2Id") Integer user2Id, @Param("message") String message, @Param("time") Date time);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbg.generated
     */
    int insert(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_record
     *
     * @mbg.generated
     */
    List<ChatRecord> selectAll();
}