package com.zubajie.dao;

import com.zubajie.entity.LendPicture;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LendPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_picture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("lendId") Integer lendId, @Param("photoUrl") String photoUrl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_picture
     *
     * @mbg.generated
     */
    int insert(LendPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_picture
     *
     * @mbg.generated
     */
    List<LendPicture> selectAll();
}