package com.zubajie.dao;

import com.zubajie.entity.LendGoods;
import java.util.List;

public interface LendGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_goods
     *
     * @mbg.generated
     */
    int insert(LendGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_goods
     *
     * @mbg.generated
     */
    LendGoods selectByPrimaryKey(Integer lendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_goods
     *
     * @mbg.generated
     */
    List<LendGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LendGoods record);
}